### ISSUE TITLE
Respmon for humans

### ISSUE THREAD

**Issue by sonineha2191** [kevroy314/respmon#1]
Have you tried working on respmon for human beings?

**Comment by kevroy314** [comment]
I've tested it on myself and it works ok, but there are a few issues with making this a human respiratory monitor. 

If it's for hobbiests (maybe you want to monitor your breathing during sleep), it will probably work fine with the right hyperparameter tuning (which is currently the challenge in general with the project - I need more ground-truth data to properly tune the hyperparameters). 

If you want to, say, monitor your respiration during a speech or while watching a movie, your natural non-respiratory movements will probably wash out too much of the signal for it to be useful. This technique works best when the individual is still/immobile. It can detect large motion and recalibrate, but if that motion is persistent, something would need to be added to remove it (which may not be possible under all conditions).

The other thing to mention is that if this was for a human medical application (say, someone in a hospital bed who is largely immobile), it would need proper regulatory approval, which is a huge task. At that point, there are other sensors that are probably a better fit.

It is interesting to mention you could use this system on non-living, periodic systems just fine. It's basically a frequency-tuned real-time motion system. So if you had, say, a weighted fan outside spinning in the wind, you could potentially measure its rotation rate (subject to your camera's frame rate), and tell the wind speed with it.

**Comment by sonineha2191** [comment]
Thank you Kevin for your quick reply.
I want to make a system to measure the respiration rate of still/immobile human beings in real time. Currently, I don't want to use this for medical purpose.

Your code is a perfect start for the same. 
Currently, the code output fluctuating between 20 to 25 bpm for me, I am working on verifying this reading.
Can you please help me:
1. According to you which hyperparameters should I tune to improve the performance?
2. Is there any other document apart from the readme file (in GitHub) where deep mathematical details and pipeline of the code have been reported?

Thanks in advance
Neha

**Comment by kevroy314** [comment]
Unfortunately, I have not published this work because I don't have a
validation data set to determine the accuracy of the model. The tunable
parameters are described in the base.py file (
https://github.com/kevroy314/respmon/blob/master/base.py#L53). A data set
of sleeping humans with labelled respiration rates and/or a data set of
animals with the same would allow me to determine the accuracy and
stability of the model and have more confidence in using it in a practical
setting. Until then, I can only anecdotally test it to determine if it
seems to be producing reasonable outputs.

I've looked into collecting this data - I have access to a good animal
population for it, but the work of actually recording, uploading, and
labelling is something I haven't gotten to yet.

**Comment by sonineha2191** [comment]
Thanks, Kevin.
I understand the level of the complexity involved.

Neha

**Comment by kevroy314** [comment]
If you have any specific questions after looking through the parameters,
I'm happy to discuss it more! I'd love to take this project to the next
level with some actual tuning/data.
